name: 'File Cancel Action'
description: 'Cancel GitHub Action workflows based on files in the repository.'
inputs:
  token:
    description: 'GitHub token used to cancel workflow, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  exists:
    description: 'Glob or multiline string of globs that cause workflow to cancel if any exist'
    required: false
  not-exists:
    description: 'Glob or multiline string of globs that cause workflow to cancel if none exist'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
